#!/usr/bin/perl
#ABSTRACT: Extract CodeBlock from Pandoc Markdown documents

use v5.14;
use JSON;

my $formatRegexp = qr/^-([a-z][a-z0-9]*)$/;

my ($format) = map { substr($_,1) if $_ =~ $formatRegexp } @ARGV;

foreach (@ARGV) {
    next if $_ =~ $formatRegexp;
    -e $_ || die "missing file $_\n";
    my $doc = JSON->new->decode(`pandoc -t json $_`);
    $doc = $doc->[1];
    foreach (@$doc) {
        next unless ref $_;
        my ($type,$content) = %{$_} eq 2 ? %{$_} : ($_->{t}, $_->{c});
        next unless $type eq 'CodeBlock';
        my $formats = $content->[0]->[1];
        next unless (!$format and !@$formats) 
             or (grep { $_ eq $format } @$formats);
        say $content->[1];
    }
}
